### ISSUE TITLE
Error when generating yelp data in YelpProcessor.ipynb

### ISSUE THREAD

**Issue by leabriand** [rootlu/MetaHIN#11]
Hello ! 

When I try to generate the data for yelp as adviced in [this issue](https://github.com/rootlu/MetaHIN/issues/6) I have the following error in the YelpProcessor.ipynb : 

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-071c77df7579> in <module>
      8     for state in states:
      9         os.mkdir("{}/{}/".format(output_dir, state))
---> 10         os.mkdir("{}/{}/".format(melu_output_dir, state))
     11         if not os.path.exists("{}/{}/{}".format(output_dir, "log", state)):
     12             os.mkdir("{}/{}/{}".format(output_dir, "log", state))

FileNotFoundError: [Errno 2] No such file or directory: '../../../MeLU/yelp//warm_up/'
```

If I understand well, I cloned [the MeLU git project](https://github.com/hoyeoplee/MeLU) but i'm not sure it is what is expected ? I don't see any yelp folder in their github project.

Thanks in advance and for the availability of your code in any case !

**Comment by rootlu** [comment]
Hi,

This line of code is to make directory for the data of baseline MeLU.
If you don't want to process data for MeLU, you can comment it.

Thanks. 
：）

**Comment by leabriand** [comment]
Hi,

Ok I see, thanks for your reply !

**Comment by rootlu** [comment]
We have also uploaded the processed data of DBook and Movielens, please refer to the updated README.
Thanks.
