### ISSUE TITLE
gcmc can not be found

### ISSUE THREAD

**Issue by weizhenzhao** [rootlu/MetaHIN#18]
Hi dear

It returns an error when I tried to running    "pip3  install -r requirements.txt" commands
can you give me some instructions? thank you very much.

thanks
weizhen
![image](https://user-images.githubusercontent.com/13706689/112587790-3184d100-8e39-11eb-928c-2ce3a25f9918.png)

**Comment by rootlu** [comment]
Hi,

[GC-MC](https://arxiv.org/abs/1706.02263) is a baseline model in our paper, it can not be directly installed by requirements.txt, sorry for the error in the requirements.txt. I have fixed it and please download the latest version.

Thanks for your interest in our work.

Bests
