### ISSUE TITLE
很想研究一下这个项目，想运行一下代码，可是我的pytorch版本不对，求pytorch和torchvision版本号

### ISSUE THREAD

**Issue by morningnn** [rootlu/MetaHIN#2]

**Comment by rootlu** [comment]
你好，

python版本是3.6.9，pytorch 的版本号是1.3.1（1.4应该也可以）, torchvision应该是没有用到的，更详细的版本可以在论文的Appendix里面找到。

感谢对我们工作的关注！

**Comment by morningnn** [comment]
好的，感恩
