### ISSUE TITLE
各种冷启动场景下train_data

### ISSUE THREAD

**Issue by heart-kong** [rootlu/MetaHIN#21]
您好，
       我在本地复现了您的MetaHIN模型，但是实验结果有较大的偏差。
       请问一下，各种冷启动场景train_data导入的都是meta_training文件夹中的数据吗？还是说不同的冷启动场景train_data导入不同的数据，比如说user冷启动场景导入的是user_cold_testing文件夹中的数据，很期待收到您的回复。

**Comment by rootlu** [comment]
你好，

meta_training是用于所有场景的训练数据，在不同冷启动场景下，对应不同的冷启动测试数据，例如user 冷启动对应user_cold_testing数据。

实验结果存在偏差是否是因为数据、参数或模型设置不准确，可以参考论文给出参数设置。

**Comment by heart-kong** [comment]
我的设想也是这样，应该是有个代码段没有运行，感谢！

**Comment by rootlu** [comment]
嗯嗯，感谢对我们工作的关注～

没有问题的话还请麻烦close一下，谢谢。
