### ISSUE TITLE
模型性能达不到论文结果的问题

### ISSUE THREAD

**Issue by HmingZ** [rootlu/MetaHIN#27]

**Comment by rootlu** [comment]
导致模型效果不如论文report结果，可以参考几个方面检查：1）实验参数是否按照论文中的参数设定，代码中参数设置有可能存在debug的设置，可结合论文附录说明进行设置；2）模型训练及测试流程是否正确，这里可以参考论文所描述的训练方式，以及检查代码执行逻辑；3）模型训练测试数据是否输入正确，模型训练和测试数据处理流程稍微复杂，可以直接使用处理好的数据，也可以自行处理，或者参考MeLu的处理方式进行处理，确保数据准确无误；4）多次实验检查结果是否存在较大波动。

**Comment by rootlu** [comment]
导致模型效果不如论文report结果，可以参考几个方面检查：1）实验参数是否按照论文中的参数设定，代码中参数设置有可能存在debug的设置，可结合论文附录说明进行设置；2）模型训练及测试流程是否正确，这里可以参考论文所描述的训练方式，以及检查代码执行逻辑；3）模型训练测试数据是否输入正确，模型训练和测试数据处理流程稍微复杂，可以直接使用处理好的数据，也可以自行处理，或者参考MeLu的处理方式进行处理，确保数据准确无误；4）多次实验检查结果是否存在较大波动。

**Comment by HmingZ** [comment]
感谢您的回复。
