### ISSUE TITLE
Something Wrong with DataProcessor.py

### ISSUE THREAD

**Issue by wanpiqiu123** [rootlu/MetaHIN#3]
Hi, when I tried to run DataProcessor.py to generate data, an error occurred.

```Traceback (most recent call last):
  File "DataProcessor.py", line 339, in <module>
    ml = Movielens(os.path.join(input_dir, 'movielens'), os.path.join(output_dir, 'movielens'))
  File "DataProcessor.py", line 30, in __init__
    self.metapath_data()
  File "DataProcessor.py", line 188, in metapath_data
    u_m_directors[(user,movie)] += list(set(self.movie_directors[movie]))
KeyError: 1259
```
I found that it's because of the keys of `movie_directors` are as `str` type while `movie` in this iteration is as `int` type.

Then I noticed that `u_m_directors.json` and `u_m_actors.json` are commented in `support_query_data` function while they still remained uncommented in `metapath_data` function, which caused the error above. Thus I wonder if these two path are useless, which means I just need to comment `u_m_directors` as well as `u_m_actors` and the problem solved.

According to my shallow understanding of the paper, these u_m_d or u_m_a paths are just temporary paths. What we want to find are u->m and u->m->sth->m, thus we don't need to store them, right?

By the way, a giant **TODO** appears at the end of `support_query_data` function, which makes me curious whether this part of your published repo is unfinished. Also, I guess the `input_dir` and `output_dir` should be 'movielens' rather than 'movielens_1m' according to the project structure. (not a big deal)

I list all my problems here:

1. How to solve this error?
2. Do we need to store `u_m_directors.json` or `u_m_actors.json`? Do we even need to calculate them?
3. Dbook & Yelp, would they works fine in data-processing with two IPython scripts? Does **TODO** matter for MovieLens?
4. How long does it take for training process (just your model, not ablation study or baselines)

Anyway, I want to personally thank you for the outstanding job. It's so nice for you to publish codes on Github. Wish you all the best in future research careers!

**Comment by rootlu** [comment]
Hi,

Sorry for the delay in reply.

A1: 
The `DataProcessor.py` is not the code for processing data, which is an obsolete file. I have deleted it. The correct code has been updated in `data/movielens/MovieLensProcessor.ipynb`, you can refer to it.

A2:
As you understand, we actually don’t need to store `u_m_directors.json` or `u_m_actors.json`. What we want are the movies that are connected via meta-paths `user-movie` or `user-movie-sth-movie`. 
Here, we calculate and store them for debugging and analyzing the dataset.

A3:
The processing codes for DBook and Yelp are correct, you can run them to generate data for our model. 
Please feel free to let me know if you have any questions about the codes. 

A4:
I don't remember the exact running time clearly. This is related to the data set and the running machine, but it will not run for a long time. During the model training process, the terminal will output training information, from which you can calculate how long the training will be completed.

Thanks for your interest in our work.


Bests,
Yuanfu

**Comment by wanpiqiu123** [comment]
Thanks a lot for your reply!

**Comment by rootlu** [comment]
We have also uploaded the processed data of DBook and Movielens, and you can run [data/yelp/YelpProcessor.ipynb](https://github.com/rootlu/MetaHIN/blob/master/data/yelp/YelpProcessor.ipynb) to generate the processed data for Yelp.  Please refer to the updated README.
Thanks.
：）
