### ISSUE TITLE
MovieLensProcessor程序问题

### ISSUE THREAD

**Issue by zbquanCoder** [rootlu/MetaHIN#4]
执行MovieLensProcessor程序时，显示Metatraining文件夹缺失support_u_movies.json，query_u_movies.json，support_u_movies_y.json文件，请问这三个文件是怎么构造出来的？

**Comment by rootlu** [comment]
你好，

抱歉没有看到提醒，及时回复。

这三个数据文件的构造是基于 meta_training.json 和 meta_training_y.json 数据的，具体实现可以参考[https://github.com/rootlu/MetaHIN/blob/master/data/yelp/YelpProcessor.ipynb](YelpProcessor) 的处理代码，基本逻辑是 筛选interaction 记录为13-100的user， 然后取末尾10次交互作为query，剩余的作为suppott，详细逻辑在论文也有描述。

由于文件太大，这三个文件暂时没有上传，后续会补充下载链接，同时也会完善MovieLensProcessor的代码。

多谢对我们工作的关注！

**Comment by rootlu** [comment]
We have also uploaded the processed data of DBook and Movielens, and you can run [data/yelp/YelpProcessor.ipynb](https://github.com/rootlu/MetaHIN/blob/master/data/yelp/YelpProcessor.ipynb) to generate the processed data for Yelp.  Please refer to the updated README.
Thanks.
：）
