### ISSUE TITLE
关于support_u_movies.json等文件的生成

### ISSUE THREAD

**Issue by love-searcher** [rootlu/MetaHIN#6]
1. 数据集的处理是使用对应的 .ipynb 文件来对原始数据进行处理
2. 在MovieLens数据集的处理文件 MovieLensProcessor.ipynb中，直接使用了非原始数据的support_u_movies.json 等文件的读取操作。
请问是否遗漏了support set和 query set的生成代码？

**Comment by rootlu** [comment]
你好，

数据处理对应的是ipynb文件；
针对movielens的处理，确实遗漏了这部分代码，后续会补全，也可参考yelp的处理代码。

多谢对我们工作的关注！

**Comment by love-searcher** [comment]
感谢回复！

**Comment by rootlu** [comment]
We have also uploaded the processed data of DBook and Movielens, and you can run [data/yelp/YelpProcessor.ipynb](https://github.com/rootlu/MetaHIN/blob/master/data/yelp/YelpProcessor.ipynb) to generate the processed data for Yelp.  Please refer to the updated README.
Thanks.
：）

**Comment by love-searcher** [comment]
Thanks.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuanfu Lu"<notifications@github.com&gt;; 
发送时间: 2020年12月6日(星期天) 下午4:15
收件人: "rootlu/MetaHIN"<MetaHIN@noreply.github.com&gt;; 
抄送: "李智源"<3470568233@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rootlu/MetaHIN] 关于support_u_movies.json等文件的生成 (#6)





 
We have also uploaded the processed data of DBook and Movielens, and you can run data/yelp/YelpProcessor.ipynb to generate the processed data for Yelp.  Please refer to the updated README.
 Thanks.
 ：）
